# Changes here will be overwritten by Copier
_commit: d87ac4b
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: "2022"
documentation: true
email: 55338215+34j@users.noreply.github.com
full_name: 34j
github_username: 34j
initial_commit: false
open_source_license: GNU General Public License v3
package_name: backtrade
project_name: Backtrade
project_short_description: A small Python package for backtesting.
project_slug: backtrade
run_poetry_install: false
setup_github: false
setup_pre_commit: false
version: 0.0.1
